Feature branch
hugopassos/Advanced-Building-Blocks-Enumerables pull request #1
Opened 2019-08-29 21:54 UTC by hugopassos

2019-08-29 23:32 UTC, bellom requested changes
Hi @hugopassos,
Well done guy, kindly be aware that you are to use `Git Flow` but instead you used `Github`, make sure to use 'Git Flow' in the next project - `OOP`
Short Explanation Hint: 
`GitHub Flow`: Pull Requests is raise from feature branches to the master.
`Git Flow`: Pull Requests is raise from feature branches to the development.

You have done well, you only need to work on `my_count`, checkout my comment.

**Kindly re-submit for review after making the changes :slightly_smiling_face: Thumps -up await you...**

2019-08-29 23:32 UTC, bellom commented on main.rb
> +  def my_count
Just one changes, and get a thumps up...
I got wrong output when i ran your code, error message below; 
![image](https://user-images.githubusercontent.com/31897434/63983050-ed92e400-cabc-11e9-8b05-bffbc11999ad.png)

2019-08-30 02:30 UTC, maelfosso requested changes
Hello,

Nice improvement. But there is still a problem.
Please, kindly read the comment left below and make the corresponding changes.
Once done, please re-submit the code review request.

Thanks

2019-08-30 02:30 UTC, maelfosso commented on main.rb
>      end
There is still a problem
```ruby
irb(main):002:0> ary = [1, 2, 4, 2]
=> [1, 2, 4, 2]
irb(main):003:0> ary.count
=> 4
irb(main):004:0> ary.my_count
=> 4
irb(main):005:0> ary.count(2)
=> 2
irb(main):006:0> ary.my_count(2)
Traceback (most recent call last):
        3: from /home/elvisfosso/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        2: from (irb):6
        1: from main.rb:60:in `my_count'
ArgumentError (wrong number of arguments (given 1, expected 0))
irb(main):007:0> ary.count{ |x| x%2 == 0 }
=> 3
irb(main):008:0> ary.my_count{ |x| x%2 == 0 }
=> 4
irb(main):009:0> 
```

2019-08-31 02:14 UTC, Ispirett requested changes
Good Job!!! :+1:  you are almost there :+1:  

Your my_each_with_index method is broken please check against the original  ruby method 
make sure they outputting the same results thanks!!

2019-08-31 21:52 UTC, Ispirett approved these changes
Great job!!!! @hugopassos you can merge this project now :1st_place_medal:

2019-09-01 07:21 UTC, merged